[custom]

ruleset=ğŸŸ æ¼ç½‘ä¹‹é±¼,[]FINAL
custom_proxy_group=ğŸŸ æ¼ç½‘ä¹‹é±¼`select`[]ğŸš€ èŠ‚ç‚¹é€‰æ‹©`[]ğŸ¯ å…¨çƒç›´è¿`[]â™»ï¸ è‡ªåŠ¨é€‰æ‹©`.*

enable_rule_generator=true
overwrite_original_rules=true

